name: 'Find closest valid package version'
description: 'Find the closest valid package version for a given python version'
inputs:
  package-name:
    description: 'The package name'
    required: true
  package-version:
    description: 'The package version'
    required: true
  python-version:
    description: 'The python version'
    required: true
outputs:
  is-valid-version:
    description:
      'Boolean value that indicates if the input package version is valid (true)
      or not (false) for the given python version'
  closed-valid-version:
    description:
      'The closed valid package version given the input package version'
runs:
  using: 'node20'
  main: 'src/main.js'
