name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  package-name: 
    description: 'The package name'
    required: true
  package-version: 
    description: 'The package version'
    required: true
  python-version: 
    description: 'The python version'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'src/main.js'
