name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # to trigger manually

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Check package version
        id: package
        uses: ./
        with:
          package-name: 'numpy'
          package-version: '2.0.2'
          python-version: '3.11'
      - name: Check package version
        uses: ./
        with:
          package-name: 'numpy'
          package-version: '2.5.2'
          python-version: '3.11'
      - name: Check package version
        uses: ./
        with:
          package-name: 'numpy'
          package-version: '1.5.2'
          python-version: '3.11'
