name: Debug
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # to trigger manually

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
          package-name: 'numpy'
          package-version: '2.0.2'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
